### ISSUE TITLE
WAS nederland draaien op nkbv/apart domein

### ISSUE THREAD

**Issue by bernardkroes** [bernardkroes/was2_tickets#14]
Te besluiten wat de domein-naam gaat worden. Bv. wedstrijden.nkbv.nl
Vervolgens 
- opzetten in overleg met Netrex (DNS en proxies). 
- mailen vanaf dit domein (email from bepalen) en zorgen dat de server namens nkbv.nl mag mailen met die naam

**Comment by RegienWinnubst** [comment]
Onze wens is 

NKBV.nl/wedstrijden (wedstrijdklimmen informatievoorziening pagina)
NKBV.nl/wedstrijden/inschrijven (voorheen https://was2.shiftf5.nl/)
NKBV.nl/wedstrijden/inschrijven/series
NKBV.nl/wedstrijden/inschrijven/nationaal
enz. enz.

**Comment by Lisaozmay** [comment]
Ik vind nkbv.nl/wedstrijden/inschrijven echt een te lange url voor communicatie middelen. Dit is niet praktisch, idee om er 
was.nkbv.nl van te maken? Het blijft immers het wedstrijd administratie systeem. 

https://was.nkbv.nl 
https://was.nkbv.nl/inschrijven
https://was.nkbv.nl/uitslagen
https://was.nkbv.nl/klimmers
https://was.nkbv.nl/teams

Reeds bestaande urls: 
https://nkbv.nl/wedstrijdsport/klimmen/ => info wedstrijdsport NKBV
https://nkbv.nl/wedstrijdsport/klimmen/nationale-wedstrijden/ => info wedstrijdsport nationale competitie NKBV
https://nkbv.nl/wedstrijdsport/klimmen/de-series/ => info wedstrijdsport de Series NKBV
