### ISSUE TITLE
Frontend: ander navigatie en aanpassingen

### ISSUE THREAD

**Issue by bernardkroes** [bernardkroes/was2_tickets#17]
Indien CMBEL akkoord (dan ook vertalingen opvragen en verwerken)
- [x] navigatie aanpassen
- [x] inschrijfscherm met toekomstige wedstrijden, eerstvolgende eerst (beperken tot 1 jaar in de toekomst?)
- [x] filters op het inschrijfscherm
- [x] inschrijfknoppen bovenaan de wedstrijdpage
- [x] uitslagen-archief
- [x] filters op het uitslagen/archief scherm (ook voor wedstrijdjaar?)
- [x] na inloggen terug naar 'landingpage'
- [x] account aanmaken: duidelijkere melding
- [x] benamingen van kalender/wedstrijden inschrijven/uitslagen
- [x] grootte en kleur van de filterknoppen
- [x] filterknop 'Alle' toevoegen bij disciplines

**Comment by bernardkroes** [comment]
[230509 - WAS wensen korte termijn.pdf](https://github.com/bernardkroes/was2_tickets/files/11479060/230509.-.WAS.wensen.korte.termijn.pdf)

**Comment by bernardkroes** [comment]
Vraag: Naast de Nationale Competitie en de Series zijn er ook wedstrijden op de 'Overige' kalender (zoals bv. DBIYO, Dockmasters, NSK, 12 uren van Dumal). Hoe moeten deze wedstrijden worden gevonden in de kalender (als er alleen maar filterknoppen zijn voor Nationaal en Series)?

**Comment by RegienWinnubst** [comment]
Ook een filterknop 'overig' aanmaken?
