### ISSUE TITLE
Series Toolbox - U18 is zonder toolbox ronde, daar worden nu vreemde punten uitgedeeld

### ISSUE THREAD

**Issue by RegienWinnubst** [bernardkroes/was2_tickets#19]
Bij de U18 zien we wel wat geks: daar hebben ze geen toolbox en daar valt dus niets op te tellen. Daar worden nu vreemde punten uitgedeeld in de uitslag (2.0, 1.0 en 0.0). Dat gaat nu goed, maar ik weet niet of dat geluk is. Weet jij of dit goed gaat?

Het gaat om deze wedstrijd: 
https://was2.shiftf5.nl/jas/competitions/4272/edit

**Comment by bernardkroes** [comment]
De punten die daar worden uitgedeeld zijn volgens de standaard bouldermethode. De ronde heeft niet het type 'Boulder (TZ toolbox)' maar is van het gewone type 'Boulder (TZtz)'.

Omdat het een standaard boulderronde is worden de scores op de standaard manier toegekend en de rondepunten worden daarna op volgorde (van hoog naar laag) toegekend (dus op basis van de '2T4 2Z3'/'1T1 2Z5' en '0T0 1Z4')
