### ISSUE TITLE
Feedback gebruikers (deelnemers wedstrijden)

### ISSUE THREAD

**Issue by RegienWinnubst** [bernardkroes/was2_tickets#23]
Hoi Bernard, 

We hebben input verzameld van de gebruiker over punten waar zij tegenaan lopen die beter kunnen. 
Het gaat hier vooral om vormgeving en bijvoorbeeld teksten die je te zien krijgt die beter kunnen. 

Ik heb de notulen hierin geplakt. Dit zijn concreet de punten:

- [x] 1.	Vindbaarheid: URL aanpassen, wedstrijdpagina duidelijk zichtbaar maken op homepage NKBV  doorgeven Bernard
- [x] 2.	Als je een account aanmaakt op https://was2.shiftf5.nl/users/sign_up wil je ook de mogelijkheid hebben bij veld Lid van: 'geen' als optie in te vullen. Het tekstje* moet boven dit veld komen te staan ipv onder en in het rood.
- [x] #27
- [x] #28
- [x] 5.	Teams: als je geen team hebt, kun je deze niet aanmaken maar moet je mailen naar NKBV. Melding toevoegen bij inschrijfproces: staat je team er niet bij? Mail naar: ....
- [x] 6.	Aanmeldvolgorde voor categorie aanpassen. De kleintjes bovenaan ipv onderaan. Dit zijn de minst ervaren deelnemers, waardoor ze zich vaak voor de verkeerde categorie inschrijven. 
- [x] #29

[230609 - WAS  feedback gebruikers.docx](https://github.com/bernardkroes/was2_tickets/files/12215869/230609.-.WAS.feedback.gebruikers.docx)

**Comment by RegienWinnubst** [comment]
@bernardkroes had jij deze ticket al gezien? Thanks!

**Comment by RegienWinnubst** [comment]
@bernardkroes. Zou je deze feedback willen verwerken?

Mensen gaan naar de site, zoeken de juiste wedstrijd zien dan: DE WEDSTRIJDRESULTATEN ZIJN NIET OPENBAAR. Deze tekst snappen mensen niet. Hier liever “Log in om je in te schrijven of resultaten te zien”

**Comment by bernardkroes** [comment]
Dit laatste commentaar is verwerkt
