### ISSUE TITLE
melding bij invoegen link

### ISSUE THREAD

**Issue by NelisCaubergs** [bernardkroes/was2_tickets#32]
Wanneer ik een link toevoeg aan de beschrijving van een event, vraagt de website om deze link toe te voegen.
Nadien kan ik niet verder werken, en moet ik teruggaan naar vorige pagina om opnieuwe te openen.

**Comment by bernardkroes** [comment]
Dit is een bekend issue in een onderliggend component dat gebruikt wordt, de huidige workaround is om de onderliggende html via het potloodje te editen.  
Dit probleem is verholpen in de ontwikkel-versie waar alle upgrades van onderliggende frameworks zijn uitgevoerd, deze kan live gaan nadat het getest is (en komt met een nieuw design voor het nkbv deel).
